version: "3.9"
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
services:
  dcp-broadcaster-db:
    image: postgres:16-alpine
    container_name: dcp-broadcaster-db
    networks:
      - dcp-broadcaster-network
    hostname: dcp-broadcaster-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dcp-broadcaster-pwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    volumes:
      - ./broadcaster-service/db/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  dcp-broadcaster-redis:
    image: redis:7.4.2-alpine
    container_name: dcp-broadcaster-redis
    networks:
      - dcp-broadcaster-network
    hostname: dcp-broadcaster-redis
    restart: always
    ports:
      - "6378:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  dcp-broadcaster-metabase:
    image: metabase/metabase:latest
    container_name: dcp-broadcaster-metabase
    networks:
      - dcp-broadcaster-network
    ports: 
      - "3000:3000"
    restart: "always"
  dcp-broadcaster-whatsapp-service:
    container_name: dcp-broadcaster-whatsapp-service
    networks:
      - dcp-broadcaster-network
    hostname: dcp-broadcaster-whatsapp-service
    build: ./whatsapp-service/
    env_file: ./whatsapp-service.env
    ports: 
      - "3550:3550"
    volumes:
      - ./whatsapp-service/sessions:/usr/src/app/sessions # Mount the local ./sessions/ folder to the container's /usr/src/app/sessions folder
    healthcheck:
      test: ["CMD-SHELL", 'netstat -ltn | grep -c ":3550"']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "always"
  dcp-broadcaster-worker:
    container_name: dcp-broadcaster-worker
    networks:
      - dcp-broadcaster-network
    build: ./broadcaster-service/
    env_file: ./dcp-broadcaster.env
    links:
      - dcp-broadcaster-db
      - dcp-broadcaster-whatsapp-service
      - dcp-broadcaster-redis
      - dcp-ollama-service
    depends_on:
      dcp-broadcaster-db:
        condition: service_healthy
      dcp-broadcaster-whatsapp-service:
        condition: service_healthy
    restart: "always"
  dcp-broadcaster-webserver:
    container_name: dcp-broadcaster-webserver
    networks:
      - dcp-broadcaster-network
    build: ./broadcaster-service/
    env_file: ./dcp-broadcaster.env
    environment:
      - SERVICE_NAME=dcp-broadcaster-webserver
    ports:
      - 3351:3351
    command: ["./dcp-broadcaster", "-mode=webserver"]
    links:
      - dcp-broadcaster-db
      - dcp-broadcaster-whatsapp-service
      - dcp-broadcaster-redis
      - dcp-ollama-service
    depends_on:
      dcp-broadcaster-db:
        condition: service_healthy
      dcp-broadcaster-whatsapp-service:
        condition: service_healthy
      dcp-broadcaster-redis:
        condition: service_healthy
    restart: "always"
  dcp-broadcaster-queues-worker:
    container_name: dcp-broadcaster-queues-worker
    networks:
      - dcp-broadcaster-network
    build: ./broadcaster-service/
    env_file: ./dcp-broadcaster.env
    environment:
      - SERVICE_NAME=dcp-broadcaster-queues-worker
    command: ["./dcp-broadcaster", "-mode=queue-worker"]
    links:
      - dcp-broadcaster-db
      - dcp-broadcaster-whatsapp-service
      - dcp-broadcaster-redis
      - dcp-ollama-service
    depends_on:
      dcp-broadcaster-db:
        condition: service_healthy
      dcp-broadcaster-whatsapp-service:
        condition: service_healthy
      dcp-broadcaster-redis:
        condition: service_healthy
    restart: "always"
  dcp-ollama-service:
    image: ollama/ollama:latest
    container_name: dcp-ollama-service
    networks:
      - dcp-broadcaster-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    # command: "-m /app/models/llama-3.2-1B.gguf"
    volumes:
      - ./ollama-service:/root/.ollama
    restart: "always"
volumes:
  db-data:
    driver: "local"
networks:
  dcp-broadcaster-network:
    name: "dcp-broadcaster-network"
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"