version: "3.9"
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
services:
  dcp-broadcaster-questions-receiver:
    container_name: dcp-broadcaster-questions-receiver
    networks:
      - dcp-broadcaster-network
    build: ../../services/broadcaster-service/
    env_file: ./dcp-broadcaster.env
    environment:
      - SERVICE_NAME=dcp-broadcaster-questions-receiver
    depends_on:
      dcp-broadcaster-db:
        condition: service_healthy
      dcp-broadcaster-whatsapp-service:
        condition: service_healthy
    restart: "always"
  dcp-broadcaster-webserver:
    container_name: dcp-broadcaster-webserver
    networks:
      - dcp-broadcaster-network
    build: ../../services/broadcaster-service/
    env_file: ./dcp-broadcaster.env
    environment:
      - SERVICE_NAME=dcp-broadcaster-webserver
    ports:
      - 3351:3351
    command: ["./dcp-broadcaster", "-mode=webserver"]
    depends_on:
      dcp-broadcaster-db:
        condition: service_healthy
      dcp-broadcaster-whatsapp-service:
        condition: service_healthy
      dcp-broadcaster-redis:
        condition: service_healthy
    restart: "always"
  dcp-broadcaster-queues-worker:
    container_name: dcp-broadcaster-queues-worker
    networks:
      - dcp-broadcaster-network
    build: ../../services/broadcaster-service/
    env_file: ./dcp-broadcaster.env
    environment:
      - SERVICE_NAME=dcp-broadcaster-queues-worker
    command: ["./dcp-broadcaster", "-mode=queue-worker"]
    restart: "always"